name: Deploy to int
on:
    push:
        branches:
            - feature/deployment
    workflow_dispatch:
jobs:
    deploy:
        uses: ndcmsl/workflows/.github/workflows/pm2-deployment.yml@feature/pm2-deployment
        with:
            remote-path: "/home/vargento/deployment/endpoint-example-typescript"
            host: ${{ secrets.SRV_HOST }}
            username: ${{ secrets.SRV_USER }}
            port: 22
            build: true
            password: ${{ secrets.SRV_PASSWORD }}
            pm2-id: "endpoint-example-typescript"