name: Deploy to int
on:
    push:
        branches:
            - feature/deployment
    workflow_dispatch:
jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - name: prueba
        uses: ndcmsl/workflows/.github/workflows/pm2-deployment.yml@feature/pm2-deployment
        with:
            remote-path: "/home/vargento/deployment/endpoint-example-typescript"
            port: 22
            build: true
            pm2-id: "endpoint-example-typescript"
        secrets:
            host: ${{ secrets.SRV_HOST }}
            username: ${{ secrets.SRV_USER }}
            password: ${{ secrets.SRV_PASSWORD }}
